apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn-deploy
  namespace: tekton-test
spec:
  workspaces:
  - name: protosource
  steps:
    - name: fetch-source-proto
      image: apipipeline-mvn
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash
        ls -alt $(workspaces.protosource.path)
        rm -rf $(workspaces.protosource.path)
        git clone https://github.azc.ext.hp.com/hp-business-platform/apimaven.git $(workspaces.protosource.path)
    - name: mvn-compile-upload-pkg
      image: apipipeline-mvn
      imagePullPolicy: IfNotPresent
      workingDir: $(workspaces.protosource.path)
      script: |
        #!/bin/bash
        mkdir -p /root/.m2
        cp ./settings.xml /root/.m2/
        mvn deploy
